name: Keep schedule alive
on:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  keepalive:
    name: Put commit in to main branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@master
